import { Command } from 'commander';
import chalk from 'chalk';
import { DEFAULT_AGENT_PROJECT_ID, DEFAULT_AGENT_DEFAULTS } from '../config/agentDefaults.js';
import { ProjectDefaults, ProjectStore, ProjectInfo } from '../config/projectStore.js';
import { restartListenerInstance } from './listener.js';
import { logProjectSummary } from '../utils/projectSummary.js';
import { promptText, promptYesNo } from '../utils/prompt.js';
import { installTerminalForProject } from '../utils/terminalInstall.js';
import { deployCommandListener } from '../utils/listenerDeploy.js';
import { deployFactoryTemplates, deployFactoryConfig, ensureAccountInIni } from '../utils/factoryAssets.js';
import { generateProjectId } from '../utils/projectId.js';

const store = new ProjectStore();

function parseBooleanFlag(value: unknown): boolean | undefined {
  if (value === undefined || value === null) return undefined;
  if (typeof value === 'boolean') return value;
  const normalized = String(value).trim().toLowerCase();
  if (['true', '1', 'yes', 'y'].includes(normalized)) return true;
  if (['false', '0', 'no', 'n'].includes(normalized)) return false;
  return undefined;
}

function buildDefaults(opts: Record<string, unknown>): ProjectDefaults {
  const defaults: ProjectDefaults = { ...DEFAULT_AGENT_DEFAULTS };
  if (typeof opts.symbol === 'string' && opts.symbol.length > 0) {
    defaults.symbol = opts.symbol;
  }
  if (typeof opts.period === 'string' && opts.period.length > 0) {
    defaults.period = opts.period;
  }
  if (typeof opts.profile === 'string' && opts.profile.length > 0) {
    defaults.profile = opts.profile;
  }
  if (typeof opts.subwindow === 'number' && Number.isFinite(opts.subwindow)) {
    defaults.subwindow = opts.subwindow;
  }
  const portable = parseBooleanFlag(opts.portable);
  if (portable !== undefined) {
    defaults.portable = portable;
  }
  return defaults;
}

export function registerInitCommand(program: Command) {
  program
    .command('init')
    .alias('up')
    .argument('[project]', 'Id do projeto (opcional; se não houver, será gerado)')
    .description('Liga o MT5 do agente, reinicia o listener e aplica defaults seguros (terminal isolado por projeto; baixa MT5 se precisar)')
    .option('--project <id>', 'Nome do projeto (alternativa à posição)')
    .option('--symbol <symbol>', 'Símbolo padrão dos comandos')
    .option('--period <period>', 'Período padrão (H1, M15, etc.)')
    .option('--subwindow <index>', 'Subjanela padrão do indicador', (val) => parseInt(val, 10))
    .option('--profile <name>', 'Perfil padrão do terminal')
    .option('--portable <flag>', 'Define portable true/false (default herdado)')
    .action(async (projectArg, opts) => {
      const file = await store.show();
      let project = projectArg || opts.project || file.last_project;
      let autogenerated = false;
      if (!project) {
        project = generateProjectId();
        autogenerated = true;
        console.log(chalk.gray(`[init] Gerado id automático: ${project}`));
      }

      const existing = file.projects[project];
      if (existing) {
        console.log(chalk.yellow(`[init] Projeto "${project}" já está criado. Use "mtcli project reset --id ${project}" para refazer na mesma pasta.`));
        return;
      }

      const confirm = await promptYesNo(`Instalar um novo terminal MT5 dedicado para '${project}'?`, true);
      if (!confirm) throw new Error('Instalação cancelada pelo usuário.');
      const install = await installTerminalForProject(project);
      const payload: ProjectInfo = {
        project,
        libs: install.libs,
        terminal: install.terminal,
        metaeditor: install.metaeditor,
        data_dir: install.dataDir,
        defaults: buildDefaults(opts),
      };
      const info = await store.setProject(project, payload, true);
      const label = autogenerated ? `${project} (auto)` : project;
      console.log(chalk.green(`[init] Projeto ${label} criado com terminal isolado.`));
      await deployCommandListener(install);
      await deployFactoryTemplates(install.dataDir);
      await deployFactoryConfig(install.dataDir);
      await ensureAccountInIni(install.dataDir);

      await restartListenerInstance({ project: info.project, profile: info.defaults?.profile ?? undefined });
      await logProjectSummary(info);
    });
}
